### ISSUE TITLE
rset not working on Linux: No such file or directory

### ISSUE THREAD

**Issue by cstrahan** [eradman/rset#13]
```
$ rset
release: 2.1
usage: rset [-elntv] [-F sshconfig_file] [-f routes_file] [-x label_pattern] hostname ...

$ cat routes.pln 
not-a-host:
	true

$ rset not-a-host
rset: true: No such file or directory
```

It looks like rset isn't working on Linux. Any idea what might be going wrong here?

I've intentionally specified a non-extant host to demonstrate that the `rset: true: No such file or directory` error is occurring locally.

**Comment by cstrahan** [comment]
Oh boy. I was looking at the man pages, and this wasn't immediately obvious (maybe it should have been -- I'm a bit sleep deprived):

I should have something like what's shown on https://scriptedconfiguration.org/:

```
# routes.pln

execute_with=sudo
interpreter=/bin/bash

10.10.0.20: mail/
→    www.pln

10.10.0.21: mail/
→    www.pln
```
```
# www.pln
interpreter=/bin/ksh -x

packages:
→    pkg_add -I ruby
→    ln -sf /usr/local/bin/{ruby27,ruby}
→    ln -sf /usr/local/bin/{irb27,irb}

services:
→    ./rinstall mail/smtpd_relay.conf /etc/mail/smtpd.conf \
→        && rcctl restart smtpd
```

The top level (`routes.pln`) is expected to have a route label per host, under which more `*.pln` files are listed -- those files then supply the host labels.

My mistake was thinking that I could place commands to execute on the remote host directly under the route labels, but the way `routes.pln` is parsed means that I was telling the parser to try to read `./true`, which is nonsensical. Makes sense now why I would see `rset: true: No such file or directory`.

Sorry for the noise.

**Comment by eradman** [comment]
Yes, the man pages don't give you a complete working example.

Tripping over this does remind me of a feature I was thinking of implementing: a script to create an a new config repo.  The problem is that this would make so many assumptions about the layout and content that represent what I _happen_ to do but do not suggest what anyone else _should_ do (using a vim modeline for example).

Installing files in `/usr/share/examples` is also a problem--this path is not standard, so I couldn't reference it with confidence from a man page.

This leaves me with examples on the home page which I can edit and update immediately.
