### ISSUE TITLE
Would love to see multi-threaded support

### ISSUE THREAD

**Issue by HanSolo71** [eradman/rset#23]
I know this is a very very very tall order but a future request I would love to see implemented is some sort of multi-threaded support. When using rset to for example update numerous machines, needing to run through each system sequentially really increases time to process.

**Comment by eradman** [comment]
@HanSolo71 I have given some thought to this. What would you say the output should look like?

**Comment by HanSolo71** [comment]
That's really hard to say in a CLI, I would say it might almost be best to forgo direct output for multi-thread and instead only list error/warnings then full output could go to a list of files for each host. That would make it easy to search or alert on errors for admins.

**Comment by eradman** [comment]
Good, with this in the mix there are three approaches to pick from 

1. Interleave output with the hostname prefix on each line
2. Fan out rset activity in separate tmux panes
3. Send output to individual log files, printing only warnings and errors

Option 1 will be very noisy, and messy given that output is non-deterministic

Option 2 may be implemented as a wrapper script, so a proof-of-concept may be worth while

Option 3 could conceivably support some kind of progress status

**Comment by HanSolo71** [comment]
- Option 1 will be very noisy, and messy given that output is
   non-deterministic
      - Noisy and hard to read, annoying to parse, and basically only
      usable by grepping or accidentally seeing the error pass by.
      - Option 2 may be implemented as a wrapper script, so a
   proof-of-concept may be worth while
      - T-Mux is a beast unto itself and something every system may not
      have installed. Furthermore if you queued up 30+ devices the number of
      panes becomes unmanageable. Seems usable in a lot of situations
but may run
      into weird limitations.
      - Option 3 could conceivably support some kind of progress status
      - This seems the best long term solution that would allow for various
      automation to be hooked in as you could parse the log files for next
      actions or warnings. You could also dump those log files into a logging
      system for monitoring of automated deployments.

**Comment by eradman** [comment]
In commit https://github.com/eradman/rset/commit/b947d5a03f90d3a6d45acb353b9a76b296b58e33 I posted an wrapper script that combines some elements of Options 2 and 3. Hopefully this serves as a useful proof-of-concept.

This implementation uses tmux, but could probably be re-written in pure shell using background jobs.

**Comment by vorakl** [comment]
@HanSolo71 , it is relatively easy to execute **rset** on a number of machines in parallel using only external "solutions". I don't see an urgent need in implementing this feature internally if a solution itself is a matter of one-liner.

While there are a number of possible options, this one, I think, is the easiest and pretty straight forward.
Let's say we have 500 machines. How would you tell **rset** to work with them?
It could be  `rset  host{0..499}`  it also could be `echo vm{0..499} | xargs rset`

xargs has a builtin support for a parallel execution. Then, our command for running **rset** on 100 machines at a time, in parallel,  will be `echo vm{0..499} | xargs -n 1 -P 100 rset`

The only problem with this command that we'll get a mess on stdout/stderr. So, we need to redirect these streams into files. I find it not very useful to separate stderr and stdout in this case, because all those error messages will be collected separately with no connections to the labels they are running from. So, it would be a bit useless.
To combine a redirection to a file and naming a file as a current hostname, it is easier to create a little wrapper, like this one: rset.sh 

```
#!/bin/sh

params="$@"
eval last_param=\$\{$#\}

rset "${params}" &> ${last_param}.log
```

The final command to run **rset** on 500 machines and on 100 machines in parallel is
`echo vm{0..499} | xargs -n 1 -P 100 ./rset.sh`

Here is my little test for running on 3 machines compare to 1 machine:

```
# run on 3 nodes
$ (TIMEFORMAT='%Rs'; time echo mykube{0..2} | xargs -n 1 -P 10 ./rset.sh)
6.866s

# run on 1 node
$ (TIMEFORMAT='%Rs'; time echo mykube0 | xargs -n 1 ./rset.sh)
6.180s
```

It works and it's not that difficult to implement.

**Comment by eradman** [comment]
@HanSolo71 this feature is implemented in PR https://github.com/eradman/rset/pull/57 _Enable parallel execution using background workers_

**Comment by eradman** [comment]
#57 merged. Closing
