### ISSUE TITLE
Local execution context

### ISSUE THREAD

**Issue by eradman** [eradman/rset#9]
In issue #7 @ winduptoy observed that it would be helpful to have a means of executing commands locally so secrets could be store in `pass` instead of storing in a git repo.

SSH has a seemly similar feature

```
ssh -o  PermitLocalCommand=yes -o LocalCommand='date > last_run' 192.168.0.2 hostname
```

Without a TTY this won't help us with `pass` and would leave plain-text passwords in the local repository.

One possible solution is to provide a new option that executes a local command to generate a remote file

```
generate_environment=./unlock.sh

192.168.0.2: wordpress/
    wordpress.pln
```

Where `rset` will

1. Execute the local command and ensure a TTY is available
2. `rset` would capture the output and write to a remote file
3. Abort and exit non-zero if the command fails

Where `unlock.sh` generates a file intended to be sourced

```sh
#!/bin/sh
cat <<EOF
SSL_CERT=$(pass show www/ssl_wildcard | head -n 1)
EOF
```

Scripts on the remote side could source this file to make use of it's contents

```
. ./env
echo $SSL_CERT
```

This example assumes shell, but the environment file could be formatted in any way (JSON, Python, ...)

**Comment by winduptoy** [comment]
The result of `generate_environment` in this case ends up as a *file* on the remote end, as it needs to be sourced in your example. Would there be any practical security benefit to parsing this generated content locally and setting these as environment variables of the SSH session? Committing to disk in one less place, perhaps?

**Comment by eradman** [comment]
I agree, putting a file in the temporary staging directory is not ideal because it has not yet been installed to it's final destination with final permissions. (This is part of the reason `rset` pipes the contents of scripts to the interpreter.)

`ssh` does have an option for setting variables

    ssh -o SendEnv="KEY" $hostname env

But this isn't practical because the server must be configured to accept each variable with `AcceptEnv`

The other challenge is that you don't want these variables to show up in the command line. Perhaps the best compromise is to set a variable and then use `exec` to continue execution with an inherited environment.

    ssh $hostname "KEY=Eegh4quu exec env"

**Comment by eradman** [comment]
Another tact that comes to mind is to create an option that generates text locally

```
interpreter=/bin/sh -u
prepend_text=./unlock.sh

etc:
    echo "$KEY"
```

Or pipe the label contents to a script which may make use of `sed` or even a real template engine

```
preprocessor=./unlock.sh

etc:
    echo '{{{KEY}}'
```

**Comment by winduptoy** [comment]
I've been pondering these options over the weekend. I think I prefer your `prepend_text` method over the `preprocessor` method because of the simplicity for my particular case (just pulling out short secrets). In my case, fussing around with `sed` or another template engine just seems like an obnoxious extra step. Maybe there are more sophisticated use cases that require that kind of power that I haven't thought of yet, however.

To summarize, here's what I'm reading:

| Method | Pros | Cons |
|----------------|--------|--------|
| `ssh / SendEnv` | Doesn't expose secrets on disk | Impractical because the server must be configured to accept it |
| `ssh / exec` | Doesn't expose secrets on disk | Vulnerable to password injection |
| `prepend_text` | Simple, flexible | Secrets exposed on disk |
| `preprocessor` | More powerful | Secrets exposed on disk, complexity |
| `generate_environment` | Simple | Secrets exposed on disk, less simple and less flexible than `prepend_text` because it demands a specific process and structure |

Obviously secrets are exposed on disk **anyways** when they land in their final destination, so maybe it's just my paranoia inflating the importance of writing them in as few places as possible. `rset` is good about cleaning up after itself in `/tmp` so maybe this isn't that big of an issue. I see that while `rset` is working, `/tmp/rset_staging_*` has permissions `775`. Maybe it would be worth considering tightening those up to `700`?

**Comment by eradman** [comment]
Very nice summary!  I made one edit to the table: normally the contents of labels are _not_ copied to disk, they are piped to the interpreter, and `prepend_text` would do the same.  Based on these pros and cons, some variation of the `prepend_text` approach is favorite.

I agree about the complexity of using a preprocessor.  This would provide a lot potential capability but would also introduce some very strange errors.

The permissions for the staging directory is worth talking about.  More on that later...

**Comment by winduptoy** [comment]
I started to take a stab at this, and I was unsure of whether to run the `prepend_text` script:
- in `ssh_command_{pipe,tty}`, which would give a unique invocation of the script per-label, making it possible to pass the label name in the environment for different results per-label
-  in `yylex`, which would produce fewer reallocations

Then I realized how convenient it would be to have the `prepend_text` script inline, e.g.:

```
local_interpreter=/usr/bin/env python3
prepend_text:
    print('SOME_VAR=foo')
    for i in range(5):
        print(f'VAR_{i}={i}')

interpreter=/bin/sh -xe
install_config:
   echo $SOME_VAR

local_interpreter=/usr/bin/env sh -e
prepend_text:
    echo "SECRET=$(pass my_secret_key)"

interpreter=/bin/sh -xe
install_secret:
   echo "$SECRET" > /etc/something
```

I realize this is half-baked and opens a whole can of worms, as `prepend_text` no longer fits the rules of pln's key=value options, but I wanted to run it by you and see what you thought of keeping it all together rather than juggling a bunch of one-liner shell scripts to pull out a single secret or something.

**Comment by eradman** [comment]
Having inline content would be useful--part of the vision I had for pln(5) was to be able to read a configuration from top to bottom without having to flip between dozens of different files as one would with an Ansible config.

Another "rule" for `.pln` files is that content not interpreted. Perhaps an exception is warranted here

```sh
interpreter=/bin/sh -xe
local_interpreter=/usr/bin/env python3

install_secret:
    !! print('SOME_VAR=foo')
    !! for i in range(5):
    !!     print(f'VAR_{i}={i}')
    echo "$SECRET" > /etc/something
```

**Comment by eradman** [comment]
Yet another attempt at contriving a syntax for inlining a block to execute locally:

```
interpreter=/bin/sh -xe
local_interpreter=/usr/bin/env python3

install_secret:
{
    print('SECRET=foo')
    for i in range(5):
        print(f'VAR_{i}={i}')
}
    echo "$SECRET" > /etc/something
```

**Comment by eradman** [comment]
I added a new function called `cmd_pipe_stdout` that should come in handy for the new local execution feature:

```c
/* tests/cmd_pipe_stdout.c */

int error_code;
int output_size;
char *output;

output = cmd_pipe_stdout(argv+1, &error_code, &output_size);
/* ... */
free(output);
```

This is for running a local command using execvp(3) and returning a buffer containing the output.

**Comment by winduptoy** [comment]
@eradman I like your curly-brace syntax best, for ease of reading, writing, and parsing.

I'm partway through taking a stab at this, but unfortunately my POSIX-foo isn't in top shape. Your `cmd_pipe_stdout` function is helpful, but I think I need pipes to both stdin and stdout (local context code --(stdin)--> `local_interpreter` --(stdout)--> prepend to remote context code). Maybe it's just late, but I'm afraid I just can't wrap my head around the whole Linux fork/pipe API... :frowning_face: 

I think I'm getting close. Mind checking out my `cmd_pipe_stdin_stdout` function and giving me any tips that come to mind? https://github.com/eradman/rset/compare/master...winduptoy:local_exec?expand=1

**Comment by eradman** [comment]
Agreed, the curly-brace syntax is good for all the reasons you mention.

The way pipe/fork/exec interact is really something! But I don't think we need a `cmd_pipe_stdin_stdout` function. Here's a sketch of how parsing can work

- match `{` : switch state flag to "local", create a temporary file (`tfd` mode `0600`)
- match `\t` : write line to `tfd`
- match anything else : error/clean up
- match `}` : close `tfd`, switch state flag back, run `local_interpreter tfname` and collect output

I would argue there's no need to pipe the contents to `local_interpreter` because the local interpreter may require some TTY input and it's reasonable to assume that the localhost you are running from is reasonably secure--an assumption that cannot be easily made for remote hosts.

The above constitutes a self-contained feature. Once this is merged and has some testes around it we can take the second step of actually making use of the output `rset` is already collecting.

**Comment by eradman** [comment]
Update: I started working on this--the parsing implementation is easy. Once I have a more complete example I'll push what I have to a branch.

**Comment by eradman** [comment]
I created the branch [local_exec](https://github.com/eradman/rset/tree/local_exec) with my work in progress on this feature.

**Comment by eradman** [comment]
Local exec feature merged. More testing required, but will track issues in new tickets

**Comment by winduptoy** [comment]
@eradman This is awesome! Thank you! It works wonderfully. Sorry for the delay, life pulled me away...

**Comment by eradman** [comment]
Thanks @winduptoy! I'm very happy with the final solution, and would not have succeeded at designing this feature without without your help.
